wandb_version: 1

learning_rate:
  desc: null
  value: 1
dataset:
  desc: null
  value: CIFAR-100
optimizer:
  desc: null
  value: your mom
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700104022.283545
    t:
      1:
      - 1
      - 35
      - 55
      2:
      - 1
      - 35
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
